FROM node:18
WORKDIR /app
COPY package*.json ./
RUN npm install
#RUN npm audit
#RUN npm audit fix
#RUN npm audit fix --force
COPY . .
RUN npm run build
# RUN npm fund
# RUN npm audit
# RUN npm audit fix --force
# Stage 2: Serve the app with Nginx
EXPOSE 3000
CMD ["npm","start"]
